#!/usr/bin/env bash
# Configure locally installed CLIs for an approved internal LLM gateway.
set -Eeuo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./configure-endpoint.sh codex --base-url URL --model MODEL \
      [--wire-api responses|chat] [--api-key-env VARIABLE]
  ./configure-endpoint.sh claude --base-url URL [--auth-token-env VARIABLE]

Codex accepts an OpenAI-compatible gateway. Claude Code requires an endpoint
compatible with Anthropic's Messages API; an OpenAI-only gateway is not enough.
No secret value is requested or written by this script.
EOF
}

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_value() {
  [[ -n "$2" ]] || fail "$1 must not be empty"
}

quote_toml() {
  local value="$1"
  [[ "$value" != *$'\n'* && "$value" != *'"'* && "$value" != *'\\'* ]] || fail "Values may not contain quotes, backslashes, or newlines"
  printf '"%s"' "$value"
}

quote_shell() {
  printf '%q' "$1"
}

validate_https_url() {
  [[ "$1" =~ ^https://[^[:space:]]+$ ]] || fail "--base-url must be an https:// URL without spaces"
}

add_source_line() {
  local rc_file="$1" env_file="$2" marker
  marker="# codex-claude-internal-endpoint"
  [[ -e "$rc_file" ]] || return 0
  grep -Fqx "$marker" "$rc_file" 2>/dev/null && return 0
  {
    printf '\n%s\n' "$marker"
    printf '[ -f %s ] && . %s\n' "$(quote_shell "$env_file")" "$(quote_shell "$env_file")"
  } >> "$rc_file"
}

configure_codex() {
  local base_url="" model="" wire_api="responses" api_key_env=""
  while (($#)); do
    case "$1" in
      --base-url) base_url="${2:-}"; shift 2 ;;
      --model) model="${2:-}"; shift 2 ;;
      --wire-api) wire_api="${2:-}"; shift 2 ;;
      --api-key-env) api_key_env="${2:-}"; shift 2 ;;
      *) usage >&2; fail "Unknown Codex option: $1" ;;
    esac
  done
  require_value --base-url "$base_url"
  require_value --model "$model"
  validate_https_url "$base_url"
  [[ "$wire_api" == "responses" || "$wire_api" == "chat" ]] || fail "--wire-api must be responses or chat"
  [[ "$api_key_env" =~ ^[A-Za-z_][A-Za-z0-9_]*$ || -z "$api_key_env" ]] || fail "Invalid --api-key-env variable name"

  local config_dir config_file
  config_dir="$HOME/.codex"
  config_file="$config_dir/config.toml"
  mkdir -p "$config_dir"
  touch "$config_file"
  grep -Fqx '[model_providers.internal-openai]' "$config_file" && fail "Provider internal-openai already exists in $config_file; edit it deliberately."
  {
    printf '\n# Managed by codex-claude-online-installer/configure-endpoint.sh\n'
    printf '[model_providers.internal-openai]\n'
    printf 'name = "Internal OpenAI-compatible gateway"\n'
    printf 'base_url = %s\n' "$(quote_toml "$base_url")"
    printf 'wire_api = %s\n' "$(quote_toml "$wire_api")"
    [[ -z "$api_key_env" ]] || printf 'env_key = %s\n' "$(quote_toml "$api_key_env")"
    printf '\n[profiles.internal]\n'
    printf 'model_provider = "internal-openai"\n'
    printf 'model = %s\n' "$(quote_toml "$model")"
  } >> "$config_file"
  printf 'Codex profile written. Start it with: codex -p internal\n'
}

configure_claude() {
  local base_url="" token_env="ANTHROPIC_AUTH_TOKEN"
  while (($#)); do
    case "$1" in
      --base-url) base_url="${2:-}"; shift 2 ;;
      --auth-token-env) token_env="${2:-}"; shift 2 ;;
      *) usage >&2; fail "Unknown Claude option: $1" ;;
    esac
  done
  require_value --base-url "$base_url"
  validate_https_url "$base_url"
  [[ "$token_env" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || fail "Invalid --auth-token-env variable name"

  local env_dir env_file
  env_dir="$HOME/.config/codex-claude-internal"
  env_file="$env_dir/claude-env.sh"
  mkdir -p -m 700 "$env_dir"
  [[ ! -e "$env_file" ]] || fail "$env_file already exists; edit it deliberately."
  {
    printf '# Generated by configure-endpoint.sh. Keep this file mode 0600.\n'
    printf 'export ANTHROPIC_BASE_URL=%s\n' "$(quote_shell "$base_url")"
    printf '# Set this in your approved secret-delivery mechanism before launching Claude Code.\n'
    printf '# export %s=\n' "$token_env"
  } > "$env_file"
  chmod 600 "$env_file"
  add_source_line "$HOME/.bashrc" "$env_file"
  add_source_line "$HOME/.zshrc" "$env_file"
  printf 'Claude environment template written to %s\n' "$env_file"
  printf 'This is valid only for an Anthropic Messages-compatible gateway.\n'
}

main() {
  (($# >= 1)) || { usage >&2; exit 2; }
  case "$1" in
    codex) shift; configure_codex "$@" ;;
    claude) shift; configure_claude "$@" ;;
    -h|--help) usage ;;
    *) usage >&2; exit 2 ;;
  esac
}

main "$@"
